### ISSUE TITLE
unknown event detail doesn't throw 404

### ISSUE THREAD

**Issue by umutbasal** [HappyHackingSpace/landing-frontend-app#49]
- https://happyhacking.space/events/lol

**Comment by atiilla** [comment]
done

```
  if (error) return notFound()
```

```
 if (!event) return (
    <LandingLayoutView>
     <Loader/>
    </LandingLayoutView>
  );
```

- Implemented a loader animation icon that displays while events are loading
- Enhances user experience by providing visual feedback during load times
- Tested to ensure loader appears only during data fetch and disappears once events are loaded
